// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, fs, getDetail, http, io, jQueriedRequest, jquery, jsdom, lists, request, search, server, socketio, stylus, _;

  request = require("request");

  jsdom = require("jsdom");

  fs = require("fs");

  jquery = fs.readFileSync("./static/js/jquery-1.7.2.min.js").toString();

  _ = require("underscore");

  _.str = require("underscore.string");

  socketio = require("socket.io");

  http = require("http");

  express = require("express");

  stylus = require("stylus");

  app = express();

  server = http.createServer(app);

  app.configure(function() {
    app.use(express.logger());
    app.use(express["static"]("" + __dirname + "/static"));
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.set("views", "" + __dirname + "/views");

  app.set("view engine", "jade");

  app.get("/", function(req, res) {
    return res.render("root");
  });

  io = socketio.listen(server);

  io.sockets.on("connection", function(socket) {
    console.log("client connected!");
    socket.on("search", function(data) {
      var query;
      query = _.str.trim(data).replace(/(\s+)/g, "+");
      return search(socket, lists["US"]["Florida"]["orlando"], query);
    });
    return socket.on("view", function(data) {
      return getDetail(socket, data);
    });
  });

  server.listen(8080);

  console.log("listening at http://localhost:8080");

  lists = require("./static/data/lists");

  jQueriedRequest = function(url, callback) {
    return jsdom.env({
      html: url,
      headers: {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.75 Safari/537.1"
      },
      src: [jquery],
      done: function(err, win) {
        if (void 0 === win) {
          return;
        }
        return callback(win.$);
      }
    });
  };

  search = function(socket, url, search) {
    return jQueriedRequest("" + url + "/search/?catAbb=sss&query=" + search, function($) {
      var $results;
      $results = $("p.row");
      return _.each($results, function(result) {
        var $link, $result, json;
        $result = $(result);
        $link = $result.find("> a");
        json = {
          date: $result.find("span.itemdate").text(),
          title: $link.text(),
          url: $link.attr("href"),
          location: $result.find("span.itempn").text()
        };
        return socket.emit("result", json);
      });
    });
  };

  getDetail = function(socket, url) {
    return jQueriedRequest(url, function($) {
      var detail, email, replyToSpan;
      detail = {
        title: $("h2").text(),
        date: $("span.postingdate").text(),
        body: $("#userbody").clone().find("ul, img, script, div").remove().end().html(),
        blurbs: [],
        images: []
      };
      replyToSpan = $("span.returnemail");
      email = replyToSpan.find("a").text();
      if (email.length) {
        detail.email = email;
      } else {
        detail.replyTo = replyToSpan.text();
      }
      $("ul.blurbs li").each(function(i, blurb) {
        return detail.blurbs.push($(blurb).text());
      });
      $("div.tn").each(function(i, div) {
        var $div;
        $div = $(div);
        return detail.images.push({
          url: $div.find("a").attr("href"),
          thumb: $div.find("img").attr("src")
        });
      });
      return socket.emit("detail", detail);
    });
  };

}).call(this);
