// Generated by CoffeeScript 1.3.3
(function() {
  var fs, jquery, jsdom, request;

  request = require("request");

  jsdom = require("jsdom");

  fs = require("fs");

  jquery = fs.readFileSync("./static/js/jquery-1.7.2.min.js").toString();

  jsdom.env({
    html: "http://www.craigslist.org/about/sites",
    src: [jquery],
    done: function(err, win) {
      var $, lists;
      if (win === void 0) {
        return;
      }
      $ = win.$;
      lists = {};
      $("div.colmask").each(function(i, col) {
        var $col, aCont, continent;
        $col = $(col);
        continent = $col.find("h1.continent_header").text();
        aCont = lists[continent] = {};
        return $col.find("div.state_delimiter").each(function(i, state) {
          var $state, aState, stateName;
          $state = $(state);
          stateName = $state.text();
          aState = aCont[stateName] = {};
          return $state.nextUntil("div.state_delimiter", "ul").find("li a").each(function(i, city) {
            var $city, name, url;
            $city = $(city);
            name = $city.text();
            url = $city.attr("href");
            return aState[name] = url;
          });
        });
      });
      return fs.writeFileSync("./static/data/lists.json", JSON.stringify(lists, null, 2));
    }
  });

}).call(this);
